#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

N_ENDPOINT="x"
N_USERNAME="x"
N_PASSWORD="x"
N_FILEPATH="x"
N_ENCRYPTION_KEY="x"
N_INTERVAL="x"

service_data() {
    echo "netinfo is starting up..."
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/local/bin/netinfo
    procd_append_param command send webdav -endpoint=${N_ENDPOINT} -username=${N_USERNAME} -password=${N_PASSWORD} -filepath=${N_FILEPATH} -encryption_key=${N_ENCRYPTION_KEY} -interval=${N_INTERVAL}
    procd_set_param pidfile /var/run/netinfo.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
