#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

N_ENDPOINT="xxx"
N_ACCESS_KEY_ID="xxx"
N_SECRET_ACCESS_KEY="xxx"
N_BUCKET="xxx"
N_OBJECT_PATH="xxx"
N_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

service_data() {
    echo "netinfo is starting up..."
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/local/bin/netinfo
    procd_append_param command send s3 -endpoint=${N_ENDPOINT} -path_style -access_key_id=${N_ACCESS_KEY_ID} -secret_access_key=${N_SECRET_ACCESS_KEY} -bucket=${N_BUCKET} -object_path=${N_OBJECT_PATH} -encryption_key=${N_ENCRYPTION_KEY} -interval=${N_INTERVAL}
    procd_set_param pidfile /var/run/netinfo.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
