#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

I_REMOTE_INTERFACE="xxx"
I_WG_INTERFACE="xxx"
I_ENDPOINT="xxx"
I_USERNAME="xxx"
I_PASSWORD="xxx"
I_FILEPATH="xxx"
I_ENCRYPTION_KEY="xxx"
I_INTERVAL="5m"

service_data() {
  echo "ipsync is starting up..."
}

start_service() {
  procd_open_instance
  procd_set_param command /usr/local/bin/ipsync
  procd_append_param command watchdog -encryption_key=${I_ENCRYPTION_KEY} -interval=${I_INTERVAL} -remote_interface=${I_REMOTE_INTERFACE} -wg_interface=${I_WG_INTERFACE} webdav -endpoint=${I_ENDPOINT} -username=${I_USERNAME} -password=${I_PASSWORD} -filepath=${I_FILEPATH}
  procd_set_param pidfile /var/run/ipsync.pid
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
