#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

service_data() {
  echo "ipsync is starting up..."
}

start_service() {
  procd_open_instance

  # env
  procd_set_param env KEY=""
  procd_append_param env INTERVAL=""
  procd_append_param env WG_REMOTE_INTERFACE=""
  procd_append_param env WG_INTERFACE=""
  procd_append_param env WEBDAV_ENDPOINT=""
  procd_append_param env WEBDAV_USERNAME=""
  procd_append_param env WEBDAV_PASSWORD=""
  procd_append_param env WEBDAV_PATH=""

  procd_set_param command /usr/local/bin/ipsync
  procd_append_param command wireguard webdav
  procd_set_param pidfile /var/run/ipsync.pid
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
