#!/bin/sh
# PROVIDE: netinfo
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr
name=netinfo
rcvar=${name}_enable
command="/usr/local/bin/netinfo"
pidfile="/var/run/${name}.pid"
start_cmd="${name}_start"

# env
N_ENDPOINT="xxx"
N_ACCESS_KEY_ID="xxx"
N_SECRET_ACCESS_KEY="xxx"
N_BUCKET="xxx"
N_OBJECT_PATH="xxx"
N_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

netinfo_start() {
  echo "Starting ${name}."
  /usr/sbin/daemon -cf -p ${pidfile} ${command} send s3 -endpoint=${N_ENDPOINT} -path_style -access_key_id=${N_ACCESS_KEY_ID} -secret_access_key=${N_SECRET_ACCESS_KEY} -bucket=${N_BUCKET} -object_path=${N_OBJECT_PATH} -encryption_key=${N_ENCRYPTION_KEY} -interval=${N_INTERVAL}
}

load_rc_config $name
run_rc_command "$1"
